stages:
    data_ingestion: 
        cmd: python src/Tutorial_Project/pipeline/stage_01_data_ingestion.py
        deps: 
            - src/Tutorial_Project/pipeline/stage_01_data_ingestion.py
            - config/config.yaml
        outs:
            - artifacts/ingested/Data
    prepare_base_model:
        cmd: python  src/Tutorial_Project/pipeline/stage_02_Prepared_Base_Model.py
        deps: 
            - src/Tutorial_Project/pipeline/stage_02_Prepared_Base_Model.py
            - config/config.yaml
        params:
            - IMAGE_SIZE
            - INCLUDE_TOP
            - WEIGHTS
            - CLASSES
            - LEARNING_RATE
        outs:
            - artifacts/prepared_base_model
    training:
        cmd: python src/Tutorial_Project/pipeline/stage_03_Training.py
        deps: 
            - src/Tutorial_Project/pipeline/stage_03_Training.py
            - config/config.yaml
            - artifacts/ingested/Data
            - artifacts/prepared_base_model
        params:
            - IMAGE_SIZE
            - EPOCHS
            - BATCH_SIZE
            - AUGMENTATION
        outs:
            - artifacts/training/model.h5
        
    evaluation:
      cmd: python src/Tutorial_Project/pipeline/stage_04_Mlflow_integeration.py
      deps:
        - src/Tutorial_Project/pipeline/stage_04_Mlflow_integeration.py
        - config/config.yaml
        - artifacts/ingested/Data
        - artifacts/training/model.h5
      params:
        - IMAGE_SIZE
        - BATCH_SIZE
      metrics:
      - scores.json:
          cache: false
        